name: sped_viewer
description: A Flutter package for generating PDF representations of Brazilian fiscal documents (NFe, CTe, NFCe, CCe).

version: 0.1.0
homepage: https://www.domanisistemas.com.br
repository: https://github.com/domani-sistemas/sped_fiscal_viewer

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: